### ISSUE TITLE
0.4.0 breaks GitHub formatters

### ISSUE THREAD

**Issue by lnestor** [pdobb/pronto-bundler_audit#2]
When running 
```
bundle exec pronto run --commit=origin/my-branch --runner=bundler_audit --formatters=github_pr
```

on v0.4.0, I get the following error:

```
bundler: failed to load command: pronto (/bundle/bin/pronto)
NoMethodError: undefined method `repo' for #<Pronto::BundlerAudit::GemfileLock::Scanner::Patch:0x00000003173ec0>
/bundle/gems/pronto-0.9.5/lib/pronto/message.rb:26:in `repo'
/bundle/gems/pronto-0.9.5/lib/pronto/message.rb:22:in `full_path'
/bundle/gems/pronto-0.9.5/lib/pronto/formatter/github_pull_request_formatter.rb:13:in `line_number'
/bundle/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:68:in `new_comment'
/bundle/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:75:in `block in new_comments'
/bundle/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:75:in `map'
/bundle/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:75:in `new_comments'
/bundle/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:7:in `format'
/bundle/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
/bundle/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
/bundle/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/bundle/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
/bundle/bin/pronto:23:in `load'
/bundle/bin/pronto:23:in `<top (required)>'
```

However it works for 0.3.0. The commit introduced a new `Patch` class to replace the one from the base `pronto` gem. I am going to investigate and hopefully have a fix soon.

**Comment by pdobb** [comment]
I see the issue and see that it runs deep. I'll be working on this soon. Thanks for the initial, insightful report and fix attempt, @lnestor .

**Comment by os6sense** [comment]
I'm issues runnin 0.3.0 now with the following error on a PR:

```
Failed to post: POST https://api.github.com/repos/XXXXXXXX/XX/pulls/6202/reviews: 422 - Invalid request.

For 'properties/position', nil is not a number. // See: https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review
```

Obviously this is an older version but with 0.4.0 failing also ...

**Comment by pdobb** [comment]
@os6sense noted, thank you. I have been traveling but plan to get to this soon. I’ve had a difficult time trying to figure out how to test github integration locally.

**Comment by os6sense** [comment]
@pdobb I've a PR in progress over at https://github.com/os6sense/pronto-bundler_audit/pull/1 - the main issue is the tight coupling in the Auditor to Pronto's git classes; really the Auditor should know nothing about Pronto. 

As you say though, the main issue is testing :)

**Comment by os6sense** [comment]
See https://github.com/pdobb/pronto-bundler_audit/pull/4 please

**Comment by pdobb** [comment]
I'm now actively working on this issue. Hope to have a working solution by this weekend.

**Comment by pdobb** [comment]
Closing as fixed by https://github.com/pdobb/pronto-bundler_audit/pull/5. Please pull latest (0.5.0) at let me know if there are any more issues. I have posted pictures to the README showing this gem working from my test app.
