### ISSUE TITLE
Provide a way to ignore specific advisories

### ISSUE THREAD

**Issue by davidstosik** [pdobb/pronto-bundler_audit#6]
Hello!
I just discovered this gem, and it looks very nice, but I have a feature request. 🤞 

BundlerAudit gives the option to ignore given advisories:
> Ignore specific advisories:
>
>     $ bundle-audit check --ignore OSVDB-108664

[The ignore list is passed to the `::Bundler::Audit::Scanner#scan` method as an Array of String option.](https://github.com/rubysec/bundler-audit/blob/ad5afdadf6b792eca6e4ae872e1bb858fa9cdc2c/lib/bundler/audit/scanner.rb#L56-L57)

It would be nice if I could pass that ignore option through Pronto.

**Comment by pdobb** [comment]
Thanks for the suggestion. I'll see if I can implement gem configuration to support options like this.

**Comment by pdobb** [comment]
Added this feature in https://github.com/pdobb/pronto-bundler_audit/pull/7.
See: https://github.com/pdobb/pronto-bundler_audit#configuration

Pronto doesn't support argument passing and the rails environment doesn't boot when running pronto. So the only option I could think of was to add a configuration file to read from.

**Comment by davidstosik** [comment]
Thank you!
