### ISSUE TITLE
NoMethodError: private method `create_pull_request_review' called for #<Pronto::Github:0x000055a3213e77f8>

### ISSUE THREAD

**Issue by skcc321** [pdobb/pronto-bundler_audit#9]
pronto 0.11.0 has changed API.
#create_pull_request_review as private method on pronto github now.

stacktrace:
```
16:19:46  NoMethodError: private method `create_pull_request_review' called for #<Pronto::Github:0x000055a3213e77f8>
16:19:46  Did you mean?  create_pull_comment
16:19:46    /usr/local/bundle/gems/pronto-bundler_audit-0.6.0/lib/formatter/github_pull_request_review_formatter.rb:18:in `submit_comments'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/git_formatter.rb:9:in `format'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto.rb:69:in `block in run'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto.rb:68:in `each'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto.rb:68:in `run'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/cli.rb:66:in `block in run'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/cli.rb:64:in `chdir'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/cli.rb:64:in `run'
16:19:46    /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
16:19:46    /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
16:19:46    /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
16:19:46    /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
16:19:46    /usr/local/bundle/gems/pronto-0.11.0/bin/pronto:6:in `<top (required)>'
16:19:46    /usr/local/bundle/bin/pronto:23:in `load'
16:19:46    /usr/local/bundle/bin/pronto:23:in `<top (required)>'
```

**Comment by skcc321** [comment]
here is the PR https://github.com/pdobb/pronto-bundler_audit/pull/10 which should fix the issue

**Comment by skcc321** [comment]
@pdobb any eta on release?

**Comment by pdobb** [comment]
@skcc321 Outlook not great. I don’t have a working environment right now. Will try over next few days.

**Comment by pdobb** [comment]
Note that I've updated the README with a "looking for a new maintainer" message.

**Comment by pdobb** [comment]
@skcc321 I'm sorry, but I don't think I will be able to help. Too much to do to get myself back to working order. Might as well just use your own branch.

**Comment by skcc321** [comment]
@pdobb how can I help you with that? BTW, I use it from my branch and it works well.

**Comment by skcc321** [comment]
@pdobb how can I help you to make it published to rubygems?

**Comment by pdobb** [comment]
@skcc321 I'd be thrilled to have help.

I can add you as an owner on the gem for rubygems so that you can publish the gem. Looks like I need your email or rubygems username, per: 
![image](https://user-images.githubusercontent.com/64674/111001118-d509b800-8348-11eb-971f-d4be333fcc40.png)

First, though, we should:
1. Bump the .version of the gem
1. Add a changelog entry describing what's in the release (just your fix, I think).

Example commit for ^ here: https://github.com/pdobb/pronto-bundler_audit/commit/46599de95b693b8eaa77b21f3b2c0c0217af5522

I could also make you a maintainer on this project so you can manage PRs etc if you'd like? Otherwise I'm happy to keep accepting PRs and merging them for now.

**Comment by skcc321** [comment]
Oh, sorry for the late response. I'm happy to help maintain the library in free time.
here is 0.6.1 PR https://github.com/pdobb/pronto-bundler_audit/pull/12

**Comment by pdobb** [comment]
I've pushed v0.7.0 to rubygems, which includes your fix. Thanks for your patience :)
